---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ template "streamsets.fullname" . }}-pv
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: {{ .Values.namespace }}
    name: {{ template "streamsets.fullname" . }}-pvc
  hostPath:
    path: {{ .Values.mnt.path }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "streamsets.fullname" . }}-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 512Mi
