apiVersion: v1
kind: Service
metadata:
  name: {{ template "streamsets.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "streamsets.fullname" . }}
    chart: {{ template "streamsets.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      name: ui
      nodePort: {{ .Values.service.permanentport }}
  selector:
    app: {{ template "streamsets.name" . }}
